### ISSUE TITLE
[제안] 로컬 개발 환경에서의 프로필 사용 정책 및 docker-compose 활용 방안

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#84]
현재 피클리에서 사용하는 application properties 프로필 정책은 다음과 같습니다.

- local: Postgres 도커
- test: Postgres 로컬 (테스트 때 사용되는 프로필이 아님)
- dev: 개발 서버 배포
- prod: 상용 서버 배포

여기서 개선이 필요하다고 생각하는 점은 다음과 같습니다:

- local 프로필과 test 프로필이 공존할 필요가 없다고 생각됩니다. (Postgres가 로컬이든 도커든 구분할 필요가 없고, 불필요합니다.)
- 테스트를 돌릴 때 test 프로필이 돌아가야 한다고 생각했는데 프로필 네이밍이 혼동의 여지가 있습니다.

그래서 다음과 같이 변경되면 좋겠습니다.

- local: Postgres
- test: 테스트용 (Postgres 또는 H2)
- dev: 유지
- prod: 유지

그래서 local 프로필은 환경변수로 DB 정보를 받을 수 있도록 하고, test 프로필은 테스트 돌릴 때만 돌아가도록 하면 좋을 것 같습니다.

그리고 예를 들어 로컬 개발 및 테스트 목적으로 다음과 같은 docker-compose.yml을 사용하는 것을 제안합니다.

```yml
version: "3"

services:
  pickly_local:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: pickly_dev
    ports:
      - 5433:5432

  pickly_test:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: pickly_test
    ports:
      - 5434:5432

volumes:
  postgres_data:
  postgres_data_test:
```

이 제안이 괜찮다면 #82 에서 해당 작업 이어나가겠습니다.
